### ISSUE TITLE
http://www.pythoscope.org/ down

### ISSUE THREAD

**Issue by mcallaghan-bsm** [mkwiatkowski/pythoscope#16]
In #15 ... maybe project is not alive anymore.
http://www.pythoscope.org/ seems to be dead too... ?

**Comment by mcallaghan-bsm** [comment]
https://www.isitdownrightnow.com/pythoscope.org.html

PythoscopeWebsite Name:
www.pythoscope.orgURL Checked:
no responseResponse Time:
unknownLast Down:
DOWN
Pythoscope.org is DOWN for everyone.
It is not just you. The server is not responding...

**Comment by mkwiatkowski** [comment]
Yep, it seems there was no point in paying for the domain year after year. The content is still available at http://pythoscope.wikidot.com I'll update the link in project description.
