### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by hjbolide** [mkwiatkowski/pythoscope#3]
I want to use [Sourcegraph](https://sourcegraph.com) for pythoscope code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/mkwiatkowski/pythoscope. (It should only take 30 seconds.)

Thank you!

**Comment by mkwiatkowski** [comment]
Done, enjoy! :)

**Comment by hjbolide** [comment]
Thanks MK !
