### ISSUE TITLE
Development status and old bugs

### ISSUE THREAD

**Issue by inktrap** [mkwiatkowski/pythoscope#7]
# Development Status

As already mentioned in the google user group … is pythoscope still alive? Who works on it? When will there be new releases?
# Launchpad

If development has moved … What about the old launchpad page and the bugs there?
Will this be migrated? [Launchpad-Bugs](https://bugs.launchpad.net/pythoscope)

**Comment by mkwiatkowski** [comment]
Hey there @inktrap. Pythoscope hasn't been worked on for some time now. If there was a bigger interest in the project I'd consider going back into developing it, but as of right now it seems people don't really need a tool like that.

**Comment by inktrap** [comment]
So what are people using instead? Their IDE? I tried pycharm and it does not seem to work as well …

**Comment by mkwiatkowski** [comment]
Pythoscope is a very specific tool - it should give you a good start in a legacy project by generating a bunch of [characterization tests](https://en.wikipedia.org/wiki/Characterization_test).

From what I see in the wild legacy projects that are important are being rewritten in a new technology with automated tests being part of the new process. It's also entirely possible to slowly refactor an existing legacy project by introducing tests manually. Michael Feathers' "Working Effectively with Legacy Code" is a good book precisely about that topic.

So it's not like you are out of options, you are out of *automated* options.

**Comment by mkwiatkowski** [comment]
@inktrap What's your use case? What do you need pythoscope for?

**Comment by inktrap** [comment]
Sometimes I don't use tdd and just start with a project.
Then there are some parts that I want to test. That's what I use
pythoscope for.

 - I generate all the sceletons for the tests automatically.
 - I move everything in a folder f.e. ``tests/todo/test_this_foo.py``
 - I write the tests for some modules/libs aso. that I need and move
   stuff out of todo so the structure of the tests represents the
   structure of the project, f.e.: ``tests/lib/test_this_foo.py``

Now I could generate this for each **function** via an IDE.
Or is there another solution? :wink:

**Comment by arita37** [comment]
Think the idea of Python Scope, generating code from source code parsing and example code are very good.

Python Scope can be transformed into API base library and most of those parts can be re-used to do more advanced automatic code generation.

Example :   
       Type inference from code source + Sample code (human based).
       Type value checking.
       Automatic documentation.
       Generate a long list of code checks (run time check).
       
       Code typing error correction using Fuzzy Logic.
